Проектная работа «Оно тебе надо»
GnMike/ono-tebe-nado pull request #1
Opened 2024-12-08 05:28 UTC by GnMike

Проектная работа «Оно тебе надо» на review.

2024-12-08 07:51 UTC, seginel requested changes
Здравствуйте, У вас получилась хорошая работа, но в ней есть замечания - здесь понадобятся доработки.

### Что понравилось

* Аккуратное форматирование кода
* Используются сематические теги
* Размечена вся структура
* Страница визуально похожа на макет
* Страница валидна
* Правильно оформлен head
* Все alt у изображений заполнены

### Что нужно поправить

* Все комментарии "Надо исправить" в коде.
* У активной ссылки по макету не должно быть подчёркивания https://disk.yandex.ru/i/-HR4F3GKVXtuOQ (под активной понимается та ссылка, которая обозначает текущую открытую страницу)
* Фиксированной высоты в большинстве случаев нужно избегать - контент может меняться, а значит высота может быть разной и она должна зависеть от содержимого. Высоту имеет смысл фиксировать для элементов, которые точно не будут меняться, например, изображения логотипов. В некоторых случаях можно использовать более мягкое свойство `min-height`, но и с ним нужно быть осторожнее - нужно точно понимать, что такой элемент не может и не должен быть меньше указанной высоты.
* При правках и написании кода придерживайтесь [общих принципов написания кода в Яндекс.Практикуме](https://code.s3.yandex.net/web-developer/verstka/%D0%9A%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%B9%D0%BB__%D0%BE%D0%B1%D1%89%D0%B8%D0%B5_%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF%D1%8B.pdf){target="_blank"}
* После внесения правок проверьте код в валидаторе https://validator.w3.org/nu/#textarea, там не должно быть критических ошибок типа ERROR. При наличии ошибок - их нужно проанализировать и исправить (если эта ошибка не противоречит другим пунктам в чеклиста к проекту).
* Стоит напомнить, что все замечания не придумываются ревьюером на ходу. Они формируются на основе чеклиста и брифа к заданию. Если соблюсти все требования чеклиста и рекомендаций в брифе, то работа будет сразу же принята. Поэтому перед отправкой на следующую итерацию рекомендую самостоятельно пройтись по брифу и чеклисту и при необходимости поправить все проблемные места. Это позволит быстрее получить зачёт по работе.

### Что можно лучше

* Все комментарии "Можно лучше" в коде.
* В разметке стоит избегать лишних обёрток <div> у элементов. Лишние обёртки хорошо бы удалять - это не повредит вёрстке, а наоборот - сделает её немного проще, уменьшит ненужную вложенность.

Комментарии "можно лучше" носят рекомендательный характер, их выполнение остается на Ваше усмотрение. Комментарии "надо исправить" являются обязательными, при выполнении всех "надо исправить" работа будет зачтена. Удачи

2024-12-08 07:51 UTC, seginel commented on index.html
> +              <span class="letter-spacing-1">Н</span>
Надо исправитЬ:
1) В именах классов не стоит использовать числа (1, 2, 3 ...), числительные (first, second, ...) или строковые представления чисел (one, two,...). Такая необходимость возникает крайне редко и обычно подобные имена явно требуются в задании на проект. Стоит помнить, что элементы по разным причинам могут менять свой порядок и элемент с классом `1` или `first` может, например, оказаться на втором месте. В именах классов прежде всего нужно отражать смысл, а не их порядковый номер в блоке.

2) Использования порядковых номеров могло бы иметь смысл, когда есть конкретная последовательная структура, которая никогда не будет меняться. Но здесь текст, он может поменяться, а при изменении текстов вполне ожидаемо, что классы могут поменять свою последовательность и вместо 1 2 3 порядок будет, например, 3 1 2 

3) Старайтесь придерживаться требований брифа. Здесь для всей строки стоит оставить общий межбуквенный отступ 0.3em , а для первой буквы `н` задать значение 0.6em (для этого у вас уже есть отдельный класс), а для последней буквы сбросить межбуквенный отступ (у вас это уже сделано)

2024-12-08 07:51 UTC, seginel commented on index.html
> +          <h1>
Отлично 
Это основной заголовок страницы. Для него верно выбран тег первого уровня. Помните, что заголовок первого уровня может быть только один на странице.

2024-12-08 07:51 UTC, seginel commented on index.html
> +
Надо исправить
Некорректно реализована структура семантических контейнеров. Напомню текст из брифа: https://disk.yandex.ru/i/fE-bSqwM-GoijA

2024-12-08 07:51 UTC, seginel commented on index.html
> +      <div class="cover">
Надо исправить 
Крупные сущности внутри `<main>` должны быть секциями. Используйте тег <section>

2024-12-08 07:51 UTC, seginel commented on index.html
> +            <a class="header__link header__link_active" href="#0">главная</a>
Надо исправить.
Активной может быть только одна ссылка. Под выбранной/активной/текущей страницей подразумевается та, которая открыта на данный момент.По рекомендации из брифа обычная ссылка может иметь класс `header__link`, а активная ссылка - два класса `header__link header__link_active`. В классе `header__link` должна содержаться общая стилизация ссылки, а для класса `header__link_active` должно быть убрано подчёркивание. Классы вы можете подобрать свои, но важно, чтобы класс активности был у одной ссылки.

2024-12-08 07:51 UTC, seginel commented on index.html
> +      <nav class="header__menu">
Отлично. Для навигационного блока использован семантический тег <nav>

2024-12-08 07:51 UTC, seginel commented on index.html
> +            <img class="footer__social-icon" src="./images/yt.svg" alt="Иконка YouTube">
Отлично 
Все alt у изображений заполнены

2024-12-08 07:51 UTC, seginel commented on index.html
> +    <link rel="stylesheet" href="./styles/style.css">
Отлично. head правильно заполнен

2024-12-08 07:51 UTC, seginel commented on index.html
> +          <a href="mailto:info@sobaka.ge">info@sobaka.ge</a><br>
Можно лучше: 
Перед параграфом тег переноса строки br стоит удалить. Параграф - это блочный элемент и он всегда начинается с новой строки.

2024-12-08 07:51 UTC, seginel commented on index.html
> +        <address class="address">
Отлично
Контактная информация обёрнута в семантический тег address

2024-12-08 07:51 UTC, seginel commented on index.html
> +        <nav>
Надо исправить. 
Это не навигационный блок. Тег nav здесь не подходит

2024-12-08 07:51 UTC, seginel commented on index.html
> +              <span class="letter-spacing-0">пафосное собрание невероятно дорогого антиквариата.</span>
Надо исправить
1) В именах классов не стоит использовать числа (1, 2, 3 ...), числительные (first, second, ...) или строковые представления чисел (one, two,...). Такая необходимость возникает крайне редко и обычно подобные имена явно требуются в задании на проект. Стоит помнить, что элементы по разным причинам могут менять свой порядок и элемент с классом `1` или `first` может, например, оказаться на втором месте. В именах классов прежде всего нужно отражать смысл, а не их порядковый номер в блоке.

2) Разные `letter-spacing` в макете у текста - это скорее ошибка макета, чем задумка дизайнера. Тексты в реальных проектах обычно вставляются контент-менеджером через админку. Тексты могут быть очень большими и расставлять в тексте обёртки `span` с определёнными классами - это нецелесообразная и трудоёмкая задача, поэтому здесь вообще стоит отказаться от использования span, а вставить просто сплошной текст. То есть здесь будет просто параграф, внутри которого текст без лишних дополнительных тегов.

2024-12-08 07:51 UTC, seginel commented on index.html
> +          <p class="cover__description-text">Аукцион вещей,<span class="whitespace"> </span>в которые<span class="whitespace"> </span>никто не<span class="whitespace"> </span>верил</p>
Надо исправить
Пустых тегов в проекте быть не должно без особой необходимости (в данной проектной работе блок overlay - это временное исключение, позже вы научитесь делать затемняющий слой и без пустого тега). В данном случае здесь сплошной текст - а в стилях подберите такое значение для свойства word-spacing, чтобы текст был близок к тому, как он отображается в макете (наиболее близо подходит значение 19px)

2024-12-08 07:51 UTC, seginel commented on index.html
> +          <button class="bet-button">Сделать ставку</button>
Можно лучше 
У кнопки в проекте хорошо бы указывать атрибут `type` с нужным значением. Подробнее: http://htmlbook.ru/html/button/type. Если данный атрибут не указать, то будет использован тип по-умолчанию `submit`, однако данный тип нужен для кнопок, которые отправляют данные в формах <form>. То есть для кнопок, которые отправляют форму, атрибут можно не указывать, для всех остальных кнопок атрибут стоит указывать. Для обычных кнопок значение атрибута должно быть `button`

2024-12-08 07:51 UTC, seginel commented on index.html
> +        <div class="about__title">Об аукционе</div>
Надо исправить 
Это заголовок. используйте тег заголовка.
 Здесь новая секция и для основного заголовка секции подойдёт второй уровень

2024-12-08 07:51 UTC, seginel commented on index.html
> +          <a class="footer__social-link" href="#0">
Можно лучше 
Ссылкам на внешние сайты можно добавить атрибут target="_blank", чтобы они открывались в новой вкладке. После того как пользователь прочитает интересующую его информацию на внешнем сайте ему будет легко вернуться на ваш сайт - нужно будет просто закрыть вкладку с внешним сайтом.

2024-12-08 07:51 UTC, seginel commented on index.html
> +             <a class="footer__menu-link footer__menu-link_active" href="#0">главная</a>
В макете вы видите, что одна из ссылок не имеет подчёркивания. Так показана ссылка, обозначающая выбранную/активную/текущую страницу, то есть ту страницу, которая открыта на данный момент. В реальном проекте мы могли бы перейти на любую из трёх страниц, тогда выбранной (или активной) стала бы другая ссылка. Активной может быть только одна ссылка. По рекомендации из брифа обычная ссылка может иметь класс `footer__menu-link`, а активная ссылка `footer__menu-link_active`. В классе `footer__menu-link` должна содержаться общая стилизация ссылки, а в стилях для класса `footer__menu-link_active` должно быть убрано подчёркивание. В стилях для класса выбранной страницы нужно убрать подчёркивание.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  grid-template-rows: 293px 2369px 366px; /* header, main, footer */
Надо исправить. Не стоит фиксировать размер грид-строк. Контент в каждой строке может поменяться и его размер будет уже другим.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +.header__links-list-item_no-bullit:focus-within, :hover {
Такого требования нет в задании и в макете. 

Согласно макету, у первого элемента в блоке навигации не должно быть буллета. Это можно реализовать через отдельный класс. В брифе рекомендуется добавить первому элементу класс `header__links-list-item_no-bullit`, а в стилях сбросить для этого класса буллет. Но есть ещё один вариант: вы ещё не изучали псевдоклассы, но метку у первого элемента можно убрать с помощью `:first-child`. При этом не потребуется дополнительный класс для этого элемента и запись будет выглядеть следующим образом:
`.header__links-list-item:first-child {
list-style: none;
}`
Эта запись применяет стиль только к первому элементу списка, убирая у него маркер.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +.header__link_active:focus, :hover {
Данного требования нет ни в макете, ни в задании

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  border-bottom: none;
Бордер должен отсутствовать только у одной ссылки, которая является активной. Реализуйте это через отдельный класс

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  background-position: -138px 0px;
Надо исправить 
Для корректного отображения по макету фоновому изображению в блоке нужен стиль `background-position: center;` + `background-size: cover;`

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +.cover__title {
Верхний регистр необходимо задать через CSS, используя свойство `text-transform` https://doka.guide/css/text-transform/. В реальных проектах текст может приходить из админки или задаваться менеджером вручную. Бывает, что по каким-либо причинам исходный текст может быть написан в нижнем регистре или содержать некоторые символы в нижнем регистре. Задав text-transform с нужным значением мы гарантируем, что любой текст будет отображаться как в макете - в верхнем регистре.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +.bet-button {
Можно лучше 
Это элемент взаимодействия с пользователем. Ему хорошо бы добавить свойство `cursor: pointer`, чтобы при наведении курсор менялся, оповещая пользователя, что это интерактивный элемент и на него можно нажать

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +}
Надо исправить
Шрифт у кнопки не по макету. Кнопке применяется браузерный шрифт по-умолчанию Arial https://disk.yandex.ru/i/wmA-RcVM_1jiBQ. Несмотря на заданный `font-family` у `body` для кнопок нужный шрифт не наследуется. Для кнопки нужно явно прописать шрифты в свойства font-family (не забыв указать тип засечек)

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +.footer__menu-link_active:focus, :hover {
Надо исправить
По макету первая ссылка в навигационном блоке не должна иметь подчёркивание. Данная ссылка обозначает активную страницу. Активной может быть любая из ссылок в навигационном блоке.

2024-12-08 07:51 UTC, seginel commented on index.html
> +            <li class="lots__card-list-item">
Надо испрваить

Количество карточек может быть больше, чем в макете. При добавлении новых карточек они должны переноситься на следующую строку и не разваливать вёрстку. А чтобы при переносе карточки выглядели красиво, в брифе есть отдельная рекомендация по стилизации: https://disk.yandex.ru/i/47OCKIihOY7Ycg. Сейчас при добавлении карточек они ломают вёрстку

https://disk.yandex.ru/i/eH6DI3L3hp869Q

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  background-image: url("../images/card-lot-02.jpg");
Надо исправить
Классы для фонового изображения не должны содержать дубли стилей, все правила кроме `background-image` следует указать через общую сущность. Перенесите в отдельный класс все стили, которые повторяются у трёх карточек.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  position: absolute;
Надо исправить
Абсолютное позиционирование должно использоваться только там, где нельзя применить статичное или относительное позиционирование. Абсолютное позиционирование убирает блок из потока и страница уже не сможет реагировать на изменение количества контента в этом блоке. Единственное место в данной проектной работе, где подходит и допускается абсолютное позиционирование - это затемняющий слой (линза) во входной секции и в карточках. В остальных местах для разметки используйте флексы и гриды, не прибегая к использованию абсолютного позиционирования

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  position: absolute;
Надо исправить
Абсолютное позиционирование должно использоваться только там, где нельзя применить статичное или относительное позиционирование. Абсолютное позиционирование убирает блок из потока и страница уже не сможет реагировать на изменение количества контента в этом блоке. Единственное место в данной проектной работе, где подходит и допускается абсолютное позиционирование - это затемняющий слой (линза) во входной секции и в карточках. В остальных местах для разметки используйте флексы и гриды, не прибегая к использованию абсолютного позиционирования

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  min-height: 105px;
Надо исправить
Не следует жёстко ограничивать высоту блока, внутри которого есть какое-то содержимое. Размер, количество элементов или количество текста внутри может измениться, контента может быть больше или меньше, чем в макете и при задании фиксированной высоты элементы могут "выпасть" из блока, тем самым сломав верстку. Любой блок должен адаптироваться по высоте под свое содержимое.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  min-height: 98px;
Надо исправить 
Не следует ограничивать высоту блока, внутри которого есть какое-то содержимое. Размер, количество элементов или количество текста внутри может измениться, контента может быть больше или меньше, чем в макете и при задании фиксированной высоты элементы могут "выпасть" из блока, тем самым сломав верстку. Любой блок должен адаптироваться по высоте под свое содержимое.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  min-height: 595px;
В этом блоке есть текст. Текст может быть разным и может занимать разную высоту. Ограничение высоты нужно удалить.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  min-height: 355px;
В этом блоке есть текст. Блоку с текстом не нужно задавать высоту (ни минимальную, ни максимальную, ни фиксированную). Высота контейнера с текстом должна зависеть от количества самого текста - если текста нет, то высота = 0, если текст есть, то высота должна автоматически подстраиваться под объём текста.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  min-height: 51px;
Надо исправить
В этом блоке есть текст. Блоку с текстом не нужно задавать высоту (ни минимальную, ни максимальную, ни фиксированную). Высота контейнера с текстом должна зависеть от количества самого текста - если текста нет, то высота = 0, если текст есть, то высота должна автоматически подстраиваться под объём текста.

2024-12-08 07:51 UTC, seginel commented on styles/style.css
> +  min-height: 692px;
Надо исправить. 
Если карточек будет меньше, то и ссылки под карточками не будет https://disk.yandex.ru/i/IgVWVKp4Ma1LLQ 
и данная высота будет меньше, чем 692px.   
Высоту здесь задавать не нужно

2024-12-08 07:51 UTC, seginel commented on index.html
> +            <p>
Надо исправить
Текста может быть меньше - отступ должен сохраняться как в макете 
https://disk.yandex.ru/i/bprGPNDMflt8kg

2024-12-11 07:07 UTC, GnMike commented on index.html
> +              <span class="letter-spacing-1">Н</span>
Исправлено.

2024-12-12 12:37 UTC, closed without merging

2024-12-12 12:37 UTC, GnMike commented
> Здравствуйте, У вас получилась хорошая работа, но в ней есть замечания - здесь понадобятся доработки.
> 
> ### Что понравилось
> * Аккуратное форматирование кода
> * Используются сематические теги
> * Размечена вся структура
> * Страница визуально похожа на макет
> * Страница валидна
> * Правильно оформлен head
> * Все alt у изображений заполнены
> 
> ### Что нужно поправить
> * Все комментарии "Надо исправить" в коде.
> * У активной ссылки по макету не должно быть подчёркивания https://disk.yandex.ru/i/-HR4F3GKVXtuOQ (под активной понимается та ссылка, которая обозначает текущую открытую страницу)
> * Фиксированной высоты в большинстве случаев нужно избегать - контент может меняться, а значит высота может быть разной и она должна зависеть от содержимого. Высоту имеет смысл фиксировать для элементов, которые точно не будут меняться, например, изображения логотипов. В некоторых случаях можно использовать более мягкое свойство `min-height`, но и с ним нужно быть осторожнее - нужно точно понимать, что такой элемент не может и не должен быть меньше указанной высоты.
> * При правках и написании кода придерживайтесь [общих принципов написания кода в Яндекс.Практикуме](https://code.s3.yandex.net/web-developer/verstka/%D0%9A%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%B9%D0%BB__%D0%BE%D0%B1%D1%89%D0%B8%D0%B5_%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF%D1%8B.pdf){target="_blank"}
> * После внесения правок проверьте код в валидаторе https://validator.w3.org/nu/#textarea, там не должно быть критических ошибок типа ERROR. При наличии ошибок - их нужно проанализировать и исправить (если эта ошибка не противоречит другим пунктам в чеклиста к проекту).
> * Стоит напомнить, что все замечания не придумываются ревьюером на ходу. Они формируются на основе чеклиста и брифа к заданию. Если соблюсти все требования чеклиста и рекомендаций в брифе, то работа будет сразу же принята. Поэтому перед отправкой на следующую итерацию рекомендую самостоятельно пройтись по брифу и чеклисту и при необходимости поправить все проблемные места. Это позволит быстрее получить зачёт по работе.
> 
> ### Что можно лучше
> * Все комментарии "Можно лучше" в коде.
> * В разметке стоит избегать лишних обёрток  у элементов. Лишние обёртки хорошо бы удалять - это не повредит вёрстке, а наоборот - сделает её немного проще, уменьшит ненужную вложенность.
> 
> Комментарии "можно лучше" носят рекомендательный характер, их выполнение остается на Ваше усмотрение. Комментарии "надо исправить" являются обязательными, при выполнении всех "надо исправить" работа будет зачтена. Удачи